language: python
python:
  - "3.6"
cache: pip
install:
  - pip install awscli
deploy:
  on:
    branch: master
  provider: s3
  detect_encoding: true
  default_text_charset: utf-8
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: juk.life
  acl: public_read
  region: ap-southeast-1
  cache_control: "max-age=21600"
after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"